gonum/matrix

mat64/cblas_test.go
mat64/dense.go
mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/format_test.go
mat64/lq.go
mat64/matrix.go
mat64/mul_test.go
mat64/vec.go

This is part of a set of changes to rationalise and centralise BLAS implementation registration.
It is expected to fail until gonum/blas#83 has been merged. Review that PR first.

Make use of gonum/blas/blas64

---

mat64/dense_test.go

This depends on gonum/blas#85, review that first.

Use harmonised panic message in test

---

mat64/dense.go
mat64/dense_test.go
mat64/format_test.go
mat64/inner_test.go
mat64/matrix.go

Add Grow method and Grower interface

---

mat64/matrix.go

Must is very cheap, we don't need to provide it.

Fixup error docs and drop Must

---

mat64/dense.go
mat64/index_no_bound_checks.go
mat64/svd.go

Remove lint

---

mat64/dense.go
mat64/dense_arithmetic.go

This is primarily from text submitted by Antoine-Lizee with modifications by Chih-Wei Chang.
Updates #112, #105, #26,

Add doc comments to Dense methods

---

mat64/dense.go
mat64/dense_arithmetic.go

Dense.{capRows,capCols} handling is currently broken. This fixes that.
See #115.
@btracey

mat64: fix Dense.{capRows,capCols} handling

---

mat64/cholesky.go
mat64/cholesky_test.go
mat64/dense.go
mat64/triangular.go

@vladimir-ch @btracey PTAL
Some times I wonder why you guys put up with my drivel.

Make Cholesky take a SymDense

---

mat64/cholesky.go
mat64/cholesky_test.go
mat64/index_bound_checks.go
mat64/index_no_bound_checks.go
mat64/triangular.go
mat64/triangular_test.go

This brings the Triangular type in line with Dense and Symmetric

Change Triangular to TriDense and add Triangular interface.

---

mat64/index_bound_checks.go
mat64/index_no_bound_checks.go

mat64: add missing doc strings

---

mat64/dense_arithmetic.go
mat64/matrix.go
mat64/vector.go
mat64/vector_test.go

Also fix doc comment on Dense DivElem.
@btracey

mat64: add element-wise arithmetic to Vector

---

mat64/vector.go

mat64: fix comment and code spelling

---

mat64/index_bound_checks.go
mat64/index_no_bound_checks.go
mat64/vector.go

mat64: remove lint

---

mat64/dense_arithmetic.go
mat64/dense_test.go

mat64: update outer product methods

---

mat64/inner.go
mat64/inner_test.go

This needs tests for Inc != 1. I'm thinking try all four of `[]struct{ incX, incY int }{{1, 1}, {1,2}, {2, 1}, {2, 2}}` in a loop with the given data. This needs then a helper to construct those vectors from the []float that are in the test struct.

mat64: make Inner take Vector type

---

mat64/dense_arithmetic.go
mat64/inner_test.go
mat64/svd_test.go

@btracey 
This was good. Found bugs with it.

mat64: fix {Mul,MulTrans} behaviour when receiver is also parameter

---

mat64/dense_arithmetic.go

@btracey 
While I was here I made things faster
```
name     old mean              new mean              delta
Exp10     102µs × (0.98,1.01)    70µs × (0.96,1.07)  -31.27% (p=0.000 n=8+10)
Exp100   14.0ms × (0.95,1.08)  13.1ms × (0.94,1.07)  -6.41% (p=0.019 n=10+10)
Exp1000   11.3s × (0.97,1.04)   11.4s × (0.97,1.03)     ~    (p=0.243 n=9+10)
```
and reduced allocations
```
benchmark            old allocs     new allocs     delta
BenchmarkExp10       138            128            -7.25%
BenchmarkExp100      204            189            -7.35%
BenchmarkExp1000     209            191            -8.61%
benchmark            old bytes     new bytes     delta
BenchmarkExp10       16608         6816          -58.96%
BenchmarkExp100      1236819       334686        -72.94%
BenchmarkExp1000 …
```

mat64: make Exp mul calls work in workspace not receiver

---

mat64/list_test.go

The current testTwoInput does not work properly with *Vector methods, such as MulVec, due to the magic performed getting Transpose{*Vector}. Rather than add yet more special cases, instead move the Transposed matrices into the types list. As an added bonus, this allows great simplification to the code as the two transpose loops can be deleted.

Fix and simplify testTwoInput.

---

mat64/dense_arithmetic.go

There are many special cases in multiplying two matrices where significant efficiencies can be gained. This PR incorporates the efficiencies that had been in MulTrans and adds the remaining cases where one of the input arguments is a Dense matrix

Add Special cases to Dense.Mul

---

mat64/dense.go
mat64/dense_test.go
mat64/symmetric.go
mat64/symmetric_test.go

mat64: check for zero sized parameter in Copy and CopySym

---

mat64/symmetric.go
mat64/symmetric_test.go

mat64: make SymDense rank methods take Vector

---

mat64/format_example_test.go

mat64: make examples visible

---

mat64/format_example_test.go

mat64: fix format example expected output

---

mat64/index_bound_checks.go
mat64/index_no_bound_checks.go
mat64/triangular.go

mat64: don't allow invalid uplo values

---

mat64/format.go
mat64/format_test.go

mat64: add column squeezing

---

mat64/index_bound_checks.go
mat64/index_no_bound_checks.go
mat64/matrix.go

mat64: make user facing panic Error type

---

mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/matrix.go

mat64: drop ApplyFunc type

---

mat64/matrix.go

This was missed.
Updates #138.

mat64: delete MulTranser

---

mat64/list_test.go
mat64/triangular.go
mat64/triangular_test.go

mat64: add TriDense source fast path to TriDense.Copy

---

mat64/lq.go
mat64/qr.go
mat64/solve.go

Following from previous discussion. Also changed `h := I` loops because of (legal but surprising) label reuse.

mat64: simplify and clarify I loops

---

mat64/cholesky_example_test.go

Add example code for computing and using Choleksy decomposition.

---

mat64/matrix.go

Fix the comment for EqualApprox

---

mat64/symmetric_test.go

mat64: fix RankTwo test for cblas

---

mat64/product.go
mat64/product_test.go

mat64: add variadic product method

---

mat64/solve_test.go

It's not entirely clear how these got into the state they were.

mat64: renable cond-dependent tests

---

mat64/product_test.go

* Check we find an optimum.
* Fix spelling.
@btracey @vladimir-ch (spelling)

mat64: improve product tests

---

mat64/cholesky_test.go
mat64/eigen_test.go
mat64/format_test.go
mat64/inner_test.go
mat64/io_test.go
mat64/matrix_test.go
mat64/pool_test.go
mat64/svd_test.go
mat64/symmetric_test.go
mat64/triangular_test.go
mat64/vector_test.go

This is the first flurry of changes to make a transition away from gocheck.

mat64: remove many gocheck Check and Assert calls

---

mat64/triangular_test.go

mat64: poison destinations prior to copy

---

mat64/pool.go
mat64/symmetric.go
mat64/symmetric_test.go

mat64: fix SymOuterK and SymRankOne

---

mat64/list_test.go

mat64: rename zero-ish names to be state aware

---

mat64/cholesky_example_test.go
mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/symmetric.go
mat64/symmetric_test.go

mat64: add scaling factor to Dense.Outer and SymDense.SymOuterK

---

mat64/matrix.go
mat64/symmetric.go

mat64: be strict with triangle for SymDense

---

mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/list_test.go
mat64/matrix_test.go
mat64/symmetric_test.go

Updates #240.
Modification for arithmetic methods was copy/paste from Add with operator change.

mat64: add list_test coverage and make methods pass

---

mat64/list_test.go
mat64/solve_test.go

mat64: fix name of SolveVec list test and error verbs

---

mat64/list_test.go
mat64/vector.go
mat64/vector_test.go

Add Vector.ScaleVec

---

mat64/matrix_test.go

mat64: reduce code duplication in Norm test

---

mat64/matrix.go
mat64/matrix_test.go

mat64: make zero sized matrices panic for Norm, Cond, Min and Max

---

mat64/matrix.go
mat64/matrix_test.go

mat64: add stack trace recovery to Maybe

---

cmat128/matrix.go
conv/conv.go

matrix/{cmat128,conv}: new packages

---

conv/conv.go
errors.go
errors_test.go
mat64/cholesky.go
mat64/dense.go
mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/eigen.go
mat64/index_bound_checks.go
mat64/index_no_bound_checks.go
mat64/inner.go
mat64/lq.go
mat64/lu.go
mat64/matrix.go
mat64/matrix_test.go
mat64/product.go
mat64/qr.go
mat64/solve.go
mat64/symmetric.go
mat64/symmetric_test.go
mat64/triangular.go
mat64/triangular_test.go
mat64/vector.go
mat64/vector_test.go

all: move errors into matrix

---

mat64/vector.go
mat64/vector_test.go

mat64: Vector clean up and some additions

---

mat64/vector.go

```
% benchstat before.txt after.txt 
name                 old time/op  new time/op  delta
ScaleVec10Inc1       41.7ns ± 1%  10.9ns ± 1%  -73.94%  (p=0.029 n=4+4)
ScaleVec100Inc1       126ns ± 1%    25ns ± 0%  -79.86%  (p=0.029 n=4+4)
ScaleVec1000Inc1      815ns ± 0%   166ns ± 0%  -79.60%  (p=0.029 n=4+4)
ScaleVec10000Inc1    10.0µs ± 0%   3.0µs ± 0%  -70.29%  (p=0.029 n=4+4)
ScaleVec100000Inc1    128µs ± 0%    52µs ± 0%  -59.69%  (p=0.029 n=4+4)
ScaleVec10Inc2       45.3ns ± 0%  16.6ns ± 0%  -63.38%  (p=0.029 n=4+4)
ScaleVec100Inc2       201ns ± 0%   106ns ± 0%  -47.33%  (p=0.029 n=4+4)
ScaleVec1000Inc2     1.59µs ± 0%  1.01µs ± 0%  -36.25%  (p=0.029 n=4+4)
ScaleVec10000Inc2    15.6µs ± 0%  10.1µs ± 0%  -35.42%  (p=0.029 n=4+4)
ScaleVec100000Inc2    182µs ± 0%   109µs ± 0%  -40.21% …
```

mat64: use asm.Dscal in Vector.ScaleVec()

---

gendoc.go
mat64/doc.go

mat64: fix documentation generation errors

---

mat64/eigen.go

set epsilon for eigen to 1e-16 to, fixes #313

---

mat64/matrix.go

mat64: RawColView returns []float64

---

mat64/dense.go
mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/list_test.go
mat64/matrix.go
mat64/mul_test.go
mat64/triangular.go
mat64/triangular_test.go
mat64/vector.go

`RowColer` and `RowColSetter` seem like the most natural options.

Rename Vectorer and VectorSetter interfaces

---

mat64/dense.go
mat64/dense_arithmetic.go
mat64/dense_test.go
mat64/list_test.go
mat64/matrix.go
mat64/mul_test.go
mat64/triangular.go
mat64/triangular_test.go
mat64/vector.go

mat64: remove RowColer and SetRowColer

---

cmat128/matrix.go
conv/conv.go

{conv,cmat128}: make cmat128.Matrix implement conjugate transpose

---

mat64/dense_test.go
mat64/matrix_test.go

Better reviewed on a per-commit basis.

Update TestRow and TestCol

---

mat64/eigen.go

mat64: make receiver names consistent

---

cmat128/doc.go
doc.go
gendoc.go
mat64/cholesky.go
mat64/dense_arithmetic.go
mat64/doc.go
mat64/lq.go
mat64/lu.go
mat64/qr.go
mat64/solve.go
mat64/vector.go

mat64: add support for vector shadowing detection

---

mat64/symmetric.go

mat64: add support for SymDense overlap detection

---

mat64/shadow.go
mat64/shadow_test.go

mat64: fix shadow boundary case

---

mat64/shadow_test.go

@gonum/developers Please take a look.

mat64: clean up redundant conditions

---

mat64/shadow.go
mat64/shadow_test.go

Fixes #357.
Needs proper tests for triangle cases. Still thinking.

mat64: implement triangle shadow detection

---

mat64/dense.go
mat64/dense_test.go
mat64/matrix.go

Fixes #351.
~~Depends on #360.~~
~~Vector case not yet complete (nor tests for this): needs proper handling of transpose - requires thought.~~

mat64: make Copy direction-aware

---

mat64/eigen.go

In some cases eigen hangs.
https://gist.github.com/idavydov/eb4c88b4663a7240c92f
It works ok with epsilon=1e-15 works, 1e-14 to be safe, as this code is going to be replaced in future.

fix issue #313 by increasing epsilon

---

mat64/dense.go
mat64/dense_arithmetic.go
mat64/qr.go

~~WIP: Waiting to add use in QFromQR.~~

mat64: add reuseAsZeroed and use in Exp

---

mat64/lu.go

... and reuse better memory in Factorize and RankOne.

mat64: add LU.Reset

---

mat64/cholesky.go

mat64: add Cholesky.Reset and panic on invalid Cholesky

---

mat64/index_bound_checks.go
mat64/index_no_bound_checks.go

Benchmarks for justification in preparation.
Approach prompted by comment by gri in the tables CL currently in review.

mat64: reduce number of comparisons for bounds checks

---

mat64/dense_arithmetic.go
mat64/dense_test.go

mat64: return Condition(inf) from Dense.Inverse for singular matrix

---

mat64/format_example_test.go

mat64: Update format example documentation to include extra verbs

---

mat64/inner.go
mat64/vector.go

@btracey @vladimir-ch @Kunde21 Please take a look.
Requires https://github.com/gonum/internal/pull/30.

mat64: use new internal/asm API

---

mat64/dense.go
mat64/symmetric.go
mat64/triangular.go
mat64/vector.go

Improve documentation about underlying types

---

mat64/svd.go

mat64: fix doc regarding thin vectors

---

mat64/eigen.go
mat64/eigen_test.go

mat64: perform Eigen decomposition

---

mat64/cholesky.go
mat64/eigen.go
mat64/gsvd.go
mat64/hogsvd.go
mat64/qr.go
mat64/svd.go

Please take a look.
Fixes #445.

matrix/mat64: remove outdated attributions to Jama code
